# Generated by Django 5.0.2 on 2024-02-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
